--T?O B?NG
CREATE TABLE KHACHHANG  
( 
    MAKH CHAR(10) NOT NULL,  
    TENKH NVARCHAR2(50),  
    DIENTHOAI CHAR(10),
    DIACHI NVARCHAR2(250),
    CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH)
);
CREATE TABLE NHANVIEN  
( 
    MANV CHAR(10) NOT NULL,  
    TENVN NVARCHAR2(50),  
    DIENTHOAI CHAR(10),
    DIACHI NVARCHAR2(250),
    CHUCVU NVARCHAR2(10),
    CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
);
CREATE TABLE MATHANG  
( 
    MAHANG CHAR(10) NOT NULL,  
    TENHANG NVARCHAR2(50),  
    NSX NVARCHAR2(50),
    GIABAN FLOAT,
    SOLUONGTON INT,
    CONSTRAINT PK_MATHANG PRIMARY KEY (MAHANG)
);
CREATE TABLE HOADON  
( 
    MAHD CHAR(10) NOT NULL,  
    MANV CHAR(10),
    MAKH CHAR(10),
    NGAYLAP DATE,
    MAHANG CHAR(10),
    TONGTIEN FLOAT,
    CONSTRAINT PK_HD PRIMARY KEY (MAHD)
);
CREATE TABLE CHITIETHD  
( 
    MAHD CHAR(10) NOT NULL,  
    MAHANG CHAR(10),
    TENHANG NVARCHAR2(50),
    SOLUONG INT,
    GIABAN FLOAT,
    THANHTIEN FLOAT,
    CONSTRAINT PK_CTHD PRIMARY KEY (MAHD)
);
--CREATE TABLE TAIKHOAN  
--( 
--    TENDANGNHAP CHAR(10),
--    MATKHAU CHAR(32)
--);
/
--TH�M KH�A NGO?I
ALTER TABLE HOADON
ADD CONSTRAINT FK_KHACHHANG_HD FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);
ALTER TABLE HOADON
ADD CONSTRAINT FK_NHANVIEN_HD FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
ALTER TABLE HOADON
ADD CONSTRAINT FK_MATHHANG_HD FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG);

ALTER TABLE CHITIETHD
ADD CONSTRAINT FK_CHITIETHD_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD);
ALTER TABLE CHITIETHD
ADD CONSTRAINT FK_CHITIETHD_MH FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG);
/
--INSERT D? LI?U
INSERT INTO KHACHHANG
VALUES ('KH001',N'B�i Ti?n Qu?c','0558392618',N'??ng Nai');
INSERT INTO KHACHHANG
VALUES ('KH002',N'Ph?m Ho�ng Ph�c','0978276354',N'Long An');
INSERT INTO KHACHHANG
VALUES ('KH003',N'L�m D??ng Di?m','0887263765',N'Ti?n Giang');
INSERT INTO KHACHHANG
VALUES ('KH004',N'L�m � H�n','0987265426',N'Th�i B�nh');

INSERT INTO NHANVIEN 
VALUES ('NV001',N'Ng� Minh T�i','0976837625',N'?� N?ng',N'Nh�n vi�n');
INSERT INTO NHANVIEN 
VALUES ('NV002',N'Tr?n B� Nh�n','0886309827',N'Phan Rang',N'Nh�n vi�n');
INSERT INTO NHANVIEN 
VALUES ('NV003',N'Nguy?n Vi?t H�n','0968721098',N'An Giang',N'Qu?n l�');
INSERT INTO NHANVIEN 
VALUES ('NV004',N'Ph?m Nh?t Linh','0565427865',N'H� N?i',N'Nh�n vi�n');

INSERT INTO MATHANG 
VALUES ('MH001',N'M�n h�nh m�y t�nh 20"','Samsung',2500000,20);
INSERT INTO MATHANG 
VALUES ('MH002','CPU Intel Core i7','Intel',300000,25);
INSERT INTO MATHANG 
VALUES ('MH003',N'Chu?t m�y t�nh kh�ng d�y','Logitech',360000,30);
INSERT INTO MATHANG 
VALUES ('MH004',N'? c?ng SSD SATA 250GB','WD',930000,40);

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';
INSERT INTO HOADON 
VALUES ('HD001','NV004','KH001','12-04-2021','MH004',930000);
INSERT INTO HOADON 
VALUES ('HD002','NV003','KH002','14-05-2021','MH003',360000);
INSERT INTO HOADON 
VALUES ('HD003','NV002','KH003','23-06-2021','MH002',300000);
INSERT INTO HOADON 
VALUES ('HD004','NV001','KH004','30-07-2021','MH001',2500000);

INSERT INTO CHITIETHD 
VALUES ('HD001','MH004',N'? c?ng SSD SATA 250GB',1,930000,930000);
INSERT INTO CHITIETHD 
VALUES ('HD002','MH003',N'Chu?t m�y t�nh kh�ng d�y',1,360000,360000);
INSERT INTO CHITIETHD 
VALUES ('HD003','MH002','CPU Intel Core i7',1,300000,300000);
INSERT INTO CHITIETHD 
VALUES ('HD004','MH001',N'M�n h�nh m�y t�nh 20"',1,2500000,2500000);

--INSERT INTO TAIKHOAN 
--VALUES ('nv001','nv001');
--INSERT INTO TAIKHOAN 
--VALUES ('nv002','nv002');
--INSERT INTO TAIKHOAN 
--VALUES ('nv003','nv003');
--INSERT INTO TAIKHOAN 
--VALUES ('nv004','nv004');
/
--------------------------------------------------------------------------------
--XEM SID
SELECT INSTANCE FROM V$THREAD;
--XEM DATABASE
SELECT NAME FROM V$DATABASE;
--XEM TH�NG TIN C�C USER
SELECT * FROM DBA_USERS;

/
SELECT INSTANCE_NUMBER, INSTANCE_NAME, STATUS, DATABASE_STATUS FROM V$INSTANCE;
SELECT DBID, NAME, CREATED, DATABASE_ROLE, DB_UNIQUE_NAME, OPEN_MODE FROM V$DATABASE;
select FILE#, CREATION_TIME, STATUS, ENABLED, CHECKPOINT_TIME from  V$DATAFILE;
SELECT SID, SERIAL#, USERNAME, SCHEMANAME, PROGRAM FROM V$SESSION;
SELECT * FROM DBA_TABLESPACES;
SELECT PID, PNAME, USERNAME, PROGRAM, BACKGROUND FROM V$PROCESS;
SELECT NUM, NAME, DISPLAY_VALUE, ISDEFAULT FROM V$PARAMETER;
SELECT USERNAME, ACCOUNT_STATUS, CREATED, EXPIRY_DATE, PROFILE, LAST_LOGIN FROM DBA_USERS;
SELECT TABLESPACE_NAME, CON_ID FROM CDB_TABLESPACES;
CREATE USER giamdoc IDENTIFIED BY giamdoc;
/
--XEM D? LI?U
SELECT * FROM KHACHHANG;
SELECT * FROM NHANVIEN;
SELECT * FROM quanly.MATHANG ORDER BY MAHANG;
SELECT * FROM HOADON;
SELECT * FROM CHITIETHD;
SELECT * FROM TAIKHOAN;
/
create or replace procedure xem_MatHang (v_cur_Mathang out sys_refcursor)
as
begin
    open v_cur_Mathang for
    select * from mathang;
end xem_MatHang;
/
variable cur_test refcursor 
exec xem_MatHang (:cur_test) 
print cur_test;
/

SET SERVEROUTPUT ON
--THỦ TỤC XEM MẶT HÀNG
CREATE OR REPLACE PROCEDURE Xem_MatHang (MA OUT CHAR, TEN OUT NVARCHAR2, X_NSX OUT NVARCHAR2, GIA OUT FLOAT, SL OUT INT)    
IS    
BEGIN    
    SELECT * INTO MA, TEN, X_NSX, GIA, SL FROM QUANLY.MATHANG;    
END;
/ --THỰC THI THỦ TỤC
DECLARE 
    V_MA MATHANG.MAHANG%TYPE;
    V_TEN MATHANG.TENHANG%TYPE;
    V_NSX MATHANG.NSX%TYPE;
    V_GIA MATHANG.GIABAN%TYPE;
    V_SL MATHANG.SOLUONGTON%TYPE;
BEGIN    
   Xem_MatHang(V_MA, V_TEN, V_NSX, V_GIA, V_SL);
   DBMS_OUTPUT.PUT_LINE('record inserted successfully');    
END;
/

SET SERVEROUTPUT ON
--THỦ TỤC THÊM MẶT HÀNG
CREATE OR REPLACE PROCEDURE Them_MatHang (MA IN CHAR, TEN IN NVARCHAR2, NSX IN NVARCHAR2, GIA IN FLOAT, SL IN INT)    
IS    
BEGIN    
    INSERT INTO MATHANG VALUES(MA, TEN, NSX, GIA, SL);    
END;
/ --THỰC THI THỦ TỤC
EXEC Them_MatHang('axc', N'CPU AMD R7', 'AMD', 2000000, 40);

--BEGIN    
--   Them_MatHang('MH007', N'XXX', 'XXX', 30000, 20);  
--   DBMS_OUTPUT.PUT_LINE('record inserted successfully');    
--END;
/

SET SERVEROUTPUT ON
--THỦ TỤC SỬA MẶT HÀNG
CREATE OR REPLACE PROCEDURE Sua_MatHang (MA IN CHAR, TEN IN NVARCHAR2, S_NSX IN NVARCHAR2, GIA IN FLOAT, SL IN INT)    
IS    
BEGIN    
    UPDATE MATHANG SET TENHANG = TEN, NSX = S_NSX, GIABAN = GIA, SOLUONGTON = SL WHERE MAHANG = MA;    
END;
/ --THỰC THI THỦ TỤC
EXEC Sua_MatHang('MH002', N'CPU Intel Core i7', 'Intel', 3000000, 50);

--BEGIN
--   Sua_MatHang('MH007', N'C', 'B', 20000, 20);  
--   DBMS_OUTPUT.PUT_LINE('record updated successfully');    
--END;
/

SET SERVEROUTPUT ON
--THỦ TỤC XÓA MẶT HÀNG
CREATE OR REPLACE PROCEDURE Xoa_MatHang (MA IN CHAR)    
IS    
BEGIN    
    DELETE FROM MATHANG WHERE MAHANG = MA;    
END;
/ --THỰC THI THỦ TỤC
EXEC Xoa_MatHang('axc');

--BEGIN    
--   Xoa_MatHang('MH007');  
--   DBMS_OUTPUT.PUT_LINE('record deleted successfully');    
--END;
/
--LAY NHUNG CO TRO CO MAT HANG LA MA 1
DECLARE 
	CURSOR C_TRO IS
	SELECT TENHANG , NSX ,GIABAN, SOLUONGTON 
	WHERE MAHANG=1;
	v_ten MATHANG.TENHANG%TYPE;
	v_nxb MATHANG.NXB%TYPE;
	v_giaban MATHANG.GIABAN%TYPE;
	v_slton MATHANG.SOLUONGTON%TYPE;
BEGIN
	OPEN C_TRO;
	FETCH C_TRO 
	INTO v_ten,v_nxb,v_giaban,v_slton
	DBMS_OUTPUT.PUT_LINE(v_ten||' '||v_nxb||' '||v_giaban||' '||vslton)
END;
---in ra nhung don hnag
DECLARE 
	CURSOR C_TRO IS
	SELECT MAHD,MANV , MAKH ,  MAHANG,  TONGTIEN
	WHERE MAHD='HD001';
	v_mahd HOADON.MAHD%TYPE;
	v_manv HOADON.MANV%TYPE;
	v_makh HOADON.MAKH%TYPE;
	v_mahang HOADON.MAHANG%TYPE;
	v_tongtien HOADON.MATONGTIEN%TYPE;
BEGIN
	OPEN C_TRO;
	FETCH C_TRO 
	INTO v_mahd,v_manv,v_makh,v_mahang,v_tongtien
	DBMS_OUTPUT.PUT_LINE(v_mahd||' '||v_manv||' '||v_makh||' '||v_mahang||' '||v_tongtien)
END

--TAO TRIGGER
CREATE OR REPLACE TRIGGER KIEMTRA_GIABAN
BEFORE INSERT OR UPDATE OF GIABAN ON MATHANG
FOR EACH ROW
BEGIN
   IF(:NEW.MAHANG IN ('MH001','MH004'))
   AND :NEW.GIABAN<300000 THEN
       RAISE_APPLICATION_ERROR(-20202,'GIA MAT HANG PHAI LON HON 300000');
   END IF;
END;
----TEST DL KHONG THOA
UPDATE MATHANG SET GIABAN=2000 WHERE MAHANG='MH004'


