/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ProfileDAO;
import POJO.ProfilePOJO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luong Vinh Khang
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Instance
     */
    DefaultTableModel dtm = new DefaultTableModel();
    
    public Profile() {
        initComponents();
        this.setTitle("Tạo Profile");
        this.setLocationRelativeTo(null);
        String []tieuDe = {"Profile", "Resource_Name", "Resource_Type", "Limit"};
        dtm.setColumnIdentifiers(tieuDe);
        tblProfile.setModel(dtm);
        hienThi();
    }
    
    public void hienThi(){
        ArrayList<ProfilePOJO> dsPrf = ProfileDAO.xemProfile();
        dtm.setRowCount(0);
        for(ProfilePOJO prf: dsPrf){
            Vector<Object> vec = new Vector<Object>();
            vec.add(prf.getProfile());
            vec.add(prf.getResource_name());
            vec.add(prf.getResource_type());
            vec.add(prf.getLimit());
            dtm.addRow(vec);
        }
        tblProfile.setModel(dtm);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenPrfl = new javax.swing.JTextField();
        txtSsnsPerUsr = new javax.swing.JTextField();
        txtCpuPerSsn = new javax.swing.JTextField();
        btnTaoProfile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfile = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtFlLgnAtmp = new javax.swing.JTextField();
        btnXoaPrf = new javax.swing.JButton();

        jLabel1.setText("Tên profile");

        jLabel2.setText("Sessions/user");

        jLabel3.setText("CPU/session");

        btnTaoProfile.setText("Tạo profile");
        btnTaoProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoProfileActionPerformed(evt);
            }
        });

        tblProfile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProfileMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProfile);

        jLabel4.setText("Failed login attempts");

        btnXoaPrf.setText("Xóa profile");
        btnXoaPrf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPrfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnXoaPrf)
                                .addGap(18, 18, 18)
                                .addComponent(btnTaoProfile))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenPrfl)
                                    .addComponent(txtSsnsPerUsr)
                                    .addComponent(txtCpuPerSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFlLgnAtmp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenPrfl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtFlLgnAtmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSsnsPerUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpuPerSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaoProfile)
                    .addComponent(btnXoaPrf))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoProfileActionPerformed
            String tenPrfl = txtTenPrfl.getText();
            String ssnsPerUsr = txtSsnsPerUsr.getText();
            String cpuPerSsn = txtCpuPerSsn.getText();
            String flLgnAtp = txtFlLgnAtmp.getText();
            ProfilePOJO prfl = new ProfilePOJO();
            prfl.setProfile(tenPrfl);
            prfl.setSsnsPerUsr(ssnsPerUsr);
            prfl.setCpuPerSssn(cpuPerSsn);
            ProfileDAO.taoProfile(tenPrfl, ssnsPerUsr, cpuPerSsn, flLgnAtp);
            hienThi();
    }//GEN-LAST:event_btnTaoProfileActionPerformed

    private void btnXoaPrfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPrfActionPerformed
        if(txtTenPrfl.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nhập tên profile cần xóa!", "Thông báo!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String tenPrf = txtTenPrfl.getText();
        ProfilePOJO sp = new ProfilePOJO();
        sp.setTenProfile(tenPrf);
        ProfileDAO.xoaProfile(tenPrf);
        hienThi();
    }//GEN-LAST:event_btnXoaPrfActionPerformed

    private void tblProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProfileMouseClicked
        int row = tblProfile.getSelectedRow();
        txtTenPrfl.setText((String) tblProfile.getValueAt(row, 0));
    }//GEN-LAST:event_tblProfileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaoProfile;
    private javax.swing.JButton btnXoaPrf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblProfile;
    private javax.swing.JTextField txtCpuPerSsn;
    private javax.swing.JTextField txtFlLgnAtmp;
    private javax.swing.JTextField txtSsnsPerUsr;
    private javax.swing.JTextField txtTenPrfl;
    // End of variables declaration//GEN-END:variables
}
