/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.SessionDAO;
import POJO.SessionPOJO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luong Vinh Khang
 */
public class Session extends javax.swing.JFrame {

    /**
     * Creates new form Instance
     */
     DefaultTableModel dtm = new DefaultTableModel();
     
    public Session() {
        initComponents();
        this.setTitle("Xem một số thông tin của Session");
        this.setLocationRelativeTo(null);
        String []tieuDe = {"SID", "SERIAL#", "USERNAME", "SCHEMANAME", "PROGRAM", "TERMINAL"};
        dtm.setColumnIdentifiers(tieuDe);
        tblSession.setModel(dtm);
        hienThi();
    }
    
    public void hienThi(){
        ArrayList<SessionPOJO> dSS = SessionDAO.xemSession();
        dtm.setRowCount(0);
        for(SessionPOJO ss: dSS){
            Vector<Object> vec = new Vector<Object>();
            vec.add(ss.getSid());
            vec.add(ss.getSerial());
            vec.add(ss.getUsername());
            vec.add(ss.getSchemaname());
            vec.add(ss.getProgram());
            vec.add(ss.getTerminal());
            dtm.addRow(vec);
        }
        tblSession.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSession = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnKillSession = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSid = new javax.swing.JTextField();
        txtSerial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnXemSessionDangChay = new javax.swing.JButton();
        btnXemTatCaSession = new javax.swing.JButton();

        tblSession.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSessionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSession);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnKillSession.setText("Kill Session");
        btnKillSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKillSessionActionPerformed(evt);
            }
        });

        jLabel1.setText("SID");

        jLabel2.setText("SERIAL#");

        btnXemSessionDangChay.setText("Xem Session đang chạy");
        btnXemSessionDangChay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemSessionDangChayActionPerformed(evt);
            }
        });

        btnXemTatCaSession.setText("Xem tất cả Session");
        btnXemTatCaSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemTatCaSessionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(txtSid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXemTatCaSession)
                    .addComponent(btnXemSessionDangChay)
                    .addComponent(btnKillSession))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnXemSessionDangChay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnXemTatCaSession))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnKillSession))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSessionMouseClicked
        // TODO add your handling code here:
        int row = tblSession.getSelectedRow();
        txtSid.setText((String) tblSession.getValueAt(row, 0));
        txtSerial.setText((String) tblSession.getValueAt(row, 1));
    }//GEN-LAST:event_tblSessionMouseClicked

    private void btnKillSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKillSessionActionPerformed
        // TODO add your handling code here:
        if(txtSid.getText().isEmpty() && txtSerial.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Chọn SID và SERIAL# cần xóa!", "Thông báo!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String sId = txtSid.getText();
        String serial = txtSerial.getText();
        SessionPOJO ss = new SessionPOJO();
        ss.setSid(sId);
        ss.setSerial(serial);
        SessionDAO.killSession(sId,serial);
//        try {
//            if(SessionDAO.killSession(sId,serial) == false)
//            {
//                JOptionPane.showMessageDialog(null, "Kill Session thất bại!");
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Kill Session thành công!");
//        }
        hienThi();
    }//GEN-LAST:event_btnKillSessionActionPerformed

    private void btnXemSessionDangChayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemSessionDangChayActionPerformed
        // TODO add your handling code here:
        ArrayList<SessionPOJO> dSS = SessionDAO.xemSessionDangChay();
        dtm.setRowCount(0);
        for(SessionPOJO ss: dSS){
            Vector<Object> vec = new Vector<Object>();
            vec.add(ss.getSid());
            vec.add(ss.getSerial());
            vec.add(ss.getUsername());
            vec.add(ss.getSchemaname());
            vec.add(ss.getProgram());
            vec.add(ss.getTerminal());
            dtm.addRow(vec);
        }
        tblSession.setModel(dtm);
    }//GEN-LAST:event_btnXemSessionDangChayActionPerformed

    private void btnXemTatCaSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemTatCaSessionActionPerformed
        // TODO add your handling code here:
        hienThi();
    }//GEN-LAST:event_btnXemTatCaSessionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Session().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKillSession;
    private javax.swing.JButton btnXemSessionDangChay;
    private javax.swing.JButton btnXemTatCaSession;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSession;
    private javax.swing.JTextField txtSerial;
    private javax.swing.JTextField txtSid;
    // End of variables declaration//GEN-END:variables
}
