/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.OracleDataProvider;
import POJO.TaoTaiKhoanPOJO;
import DAO.TaoTaiKhoanDAO;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import javax.swing.JComboBox;

/**
 *
 * @author Luong Vinh Khang
 */
public class TaoTaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form TaoTaiKhoan
     */
    DefaultTableModel dtmTblspc = new DefaultTableModel();
    DefaultTableModel dtmUser = new DefaultTableModel();
    
    public TaoTaiKhoan() {
        initComponents();
        this.setTitle("Quản lý Người dùng");
        this.setLocationRelativeTo(null);
        
        String []tieuDe = {"USERNAME", "ACCOUNT_STATUS", "CREATED", "EXPIRY_DATE" , "PROFILE" , "LAST_LOGIN", "TABLESPACE_NAME"};
        dtmUser.setColumnIdentifiers(tieuDe);
        tblNguoiDung.setModel(dtmUser);
        hienThi();
        
        String sqlCbbTblsp = "SELECT TABLESPACE_NAME FROM CDB_TABLESPACES";
        loadDuLieuCbbox(sqlCbbTblsp, this.cbbTblsp, "TABLESPACE_NAME");
        String sqlCbbTmpTblsp = "SELECT TABLESPACE_NAME FROM CDB_TABLESPACES";
        loadDuLieuCbbox(sqlCbbTmpTblsp, this.cbbTmpTblsp, "TABLESPACE_NAME");
        String sqlCbbTenPrfl = "SELECT distinct Profile FROM DBA_PROFILES";
        loadDuLieuCbbox(sqlCbbTenPrfl, this.cbbTenPrfl, "Profile");
        //loadDuLieuCbbox();
    }
    
    public void hienThi(){
        ArrayList<TaoTaiKhoanPOJO> dsUsr = TaoTaiKhoanDAO.xemNguoiDung();
        dtmUser.setRowCount(0);
        for(TaoTaiKhoanPOJO usr: dsUsr){
            Vector<Object> vec = new Vector<Object>();
            vec.add(usr.getUsername());
            vec.add(usr.getAccStts());
            vec.add(usr.getCreated());
            vec.add(usr.getExDate());
            vec.add(usr.getProfile());
            vec.add(usr.getLstLgin());
            vec.add(usr.getTblspNm());
            dtmUser.addRow(vec);
        }
        tblNguoiDung.setModel(dtmUser);
    }
    
    public void loadDuLieuCbbox(String sql, JComboBox cbb, String bien)
    {
        try {
            OracleDataProvider provider = new OracleDataProvider();
            provider.open(DangNhap.sid, DangNhap.usn, DangNhap.pwd);
            ResultSet rs = provider.executeQuery(sql);
            while(rs.next()){
                cbb.addItem(rs.getString(bien));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không thể nạp dữ liệu!", "Lỗi!", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
//    public void loadDuLieuCbbox()
//    {
//        String sql = "SELECT TABLESPACE_NAME FROM CDB_TABLESPACES";
//        try {
//            OracleDataProvider provider = new OracleDataProvider();
//            provider.open(DangNhap.sid, DangNhap.usn, DangNhap.pwd);
//            ResultSet rs = provider.executeQuery(sql);
//            while(rs.next()){
//                this.cbbTblsp.addItem(rs.getString("TABLESPACE_NAME"));
//                this.cbbTmpTblsp.addItem(rs.getString("TABLESPACE_NAME"));
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Lỗi!", "Thông báo!",JOptionPane.INFORMATION_MESSAGE);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnGanVaiToHT = new javax.swing.JButton();
        btnThuHoiVaiToHT = new javax.swing.JButton();
        btnGanQuyenKN = new javax.swing.JButton();
        btnThuHoiQuyenKN = new javax.swing.JButton();
        btnGanQuyenDT = new javax.swing.JButton();
        btnThuHoiQuyenDT = new javax.swing.JButton();
        btnTaoUser = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNguoiDung = new javax.swing.JTable();
        txtPwd = new javax.swing.JPasswordField();
        btnXoaNguoiDung = new javax.swing.JButton();
        btnDoiMK = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbbTmpTblsp = new javax.swing.JComboBox<>();
        cbbTblsp = new javax.swing.JComboBox<>();
        btnNote = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbbTenPrfl = new javax.swing.JComboBox<>();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("PHÂN QUYỀN"));

        btnGanVaiToHT.setText("Gán vai trò hệ thống");
        btnGanVaiToHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanVaiToHTActionPerformed(evt);
            }
        });

        btnThuHoiVaiToHT.setText("Thu hồi vai trò hệ thống");
        btnThuHoiVaiToHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuHoiVaiToHTActionPerformed(evt);
            }
        });

        btnGanQuyenKN.setText("Gán quyền kết nối");
        btnGanQuyenKN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanQuyenKNActionPerformed(evt);
            }
        });

        btnThuHoiQuyenKN.setText("Thu hồi quyền kết nối");
        btnThuHoiQuyenKN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuHoiQuyenKNActionPerformed(evt);
            }
        });

        btnGanQuyenDT.setText("Gán quyền đối tượng");
        btnGanQuyenDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanQuyenDTActionPerformed(evt);
            }
        });

        btnThuHoiQuyenDT.setText("Thu hồi quyền đối tượng");
        btnThuHoiQuyenDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuHoiQuyenDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGanQuyenKN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThuHoiQuyenKN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThuHoiQuyenDT)
                    .addComponent(btnGanQuyenDT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGanVaiToHT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThuHoiVaiToHT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnGanQuyenDT, btnGanQuyenKN, btnGanVaiToHT, btnThuHoiQuyenDT, btnThuHoiQuyenKN, btnThuHoiVaiToHT});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGanVaiToHT)
                    .addComponent(btnGanQuyenKN)
                    .addComponent(btnGanQuyenDT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThuHoiVaiToHT)
                    .addComponent(btnThuHoiQuyenKN)
                    .addComponent(btnThuHoiQuyenDT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTaoUser.setText("Tạo người dùng");
        btnTaoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoUserActionPerformed(evt);
            }
        });

        jLabel2.setText("Mật khẩu");

        jLabel1.setText("Tên người dùng");

        tblNguoiDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNguoiDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNguoiDungMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNguoiDung);

        btnXoaNguoiDung.setText("Xóa người dùng");
        btnXoaNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNguoiDungActionPerformed(evt);
            }
        });

        btnDoiMK.setText("Đổi mật khẩu");
        btnDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMKActionPerformed(evt);
            }
        });

        jLabel3.setText("Tablespace");

        jLabel4.setText("Temporary Tablespace");

        btnNote.setText("Note");
        btnNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoteActionPerformed(evt);
            }
        });

        jLabel5.setText("Tên profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPwd)
                                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbbTmpTblsp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbbTblsp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnXoaNguoiDung)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDoiMK)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnTaoUser)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbTenPrfl, 0, 87, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNote)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(cbbTblsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(cbbTenPrfl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(cbbTmpTblsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnNote))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaoUser)
                    .addComponent(btnXoaNguoiDung)
                    .addComponent(btnDoiMK))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoUserActionPerformed
        String tenND  = txtUserName.getText();
        String mk = txtPwd.getText();
        String tblsp  = cbbTblsp.getSelectedItem().toString();
        String tmpTblsp  = cbbTmpTblsp.getSelectedItem().toString();
        String prf  = cbbTenPrfl.getSelectedItem().toString();
        TaoTaiKhoanPOJO ttk = new TaoTaiKhoanPOJO();
        ttk.setUsrNm(tenND);
        ttk.setPwd(mk);
        TaoTaiKhoanDAO.taoTaiKhoan(tenND, mk, tblsp, tmpTblsp, prf);
        hienThi();
    }//GEN-LAST:event_btnTaoUserActionPerformed

    private void btnXoaNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNguoiDungActionPerformed
        String tenND  = txtUserName.getText();
        TaoTaiKhoanPOJO ttk = new TaoTaiKhoanPOJO();
        ttk.setUsrNm(tenND);
        TaoTaiKhoanDAO.xoaTaiKhoan(tenND);
        hienThi();
    }//GEN-LAST:event_btnXoaNguoiDungActionPerformed

    private void btnDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMKActionPerformed
        String tenND  = txtUserName.getText();
        String matKhauND  = txtPwd.getText();
        TaoTaiKhoanPOJO ttk = new TaoTaiKhoanPOJO();
        ttk.setUsrNm(tenND);
        TaoTaiKhoanDAO.doiMatKhau(tenND, matKhauND);
    }//GEN-LAST:event_btnDoiMKActionPerformed

    private void tblNguoiDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNguoiDungMouseClicked
        // TODO add your handling code here:
        int row = tblNguoiDung.getSelectedRow();
        txtUserName.setText((String) tblNguoiDung.getValueAt(row, 0));
    }//GEN-LAST:event_tblNguoiDungMouseClicked

    private void btnGanVaiToHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanVaiToHTActionPerformed
        String tenND  = txtUserName.getText();
        TaoTaiKhoanPOJO ttk = new TaoTaiKhoanPOJO();
        ttk.setUsrNm(tenND);
        TaoTaiKhoanDAO.ganVaiTroHT(tenND);
    }//GEN-LAST:event_btnGanVaiToHTActionPerformed

    private void btnThuHoiVaiToHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuHoiVaiToHTActionPerformed
        String tenND  = txtUserName.getText();
        TaoTaiKhoanPOJO ttk = new TaoTaiKhoanPOJO();
        ttk.setUsrNm(tenND);
        TaoTaiKhoanDAO.thuHoiVaiTroHT(tenND);
    }//GEN-LAST:event_btnThuHoiVaiToHTActionPerformed

    private void btnGanQuyenKNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanQuyenKNActionPerformed
        String tenND  = txtUserName.getText();
        TaoTaiKhoanPOJO ttk = new TaoTaiKhoanPOJO();
        ttk.setUsrNm(tenND);
        TaoTaiKhoanDAO.ganQuyenKN(tenND);
    }//GEN-LAST:event_btnGanQuyenKNActionPerformed

    private void btnThuHoiQuyenKNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuHoiQuyenKNActionPerformed
        String tenND  = txtUserName.getText();
        TaoTaiKhoanPOJO ttk = new TaoTaiKhoanPOJO();
        ttk.setUsrNm(tenND);
        TaoTaiKhoanDAO.thuHoiQuyenKN(tenND);
    }//GEN-LAST:event_btnThuHoiQuyenKNActionPerformed

    private void btnGanQuyenDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanQuyenDTActionPerformed
//        String tenND  = txtUserName.getText();
//        TaoTaiKhoanPOJO ttk = new TaoTaiKhoanPOJO();
//        ttk.setUsrNm(tenND);
//        TaoTaiKhoanDAO.ganQuyenDT(tenND);
        
        GanQuyenDT frmGQDT = new GanQuyenDT();
        frmGQDT.setVisible(true);
    }//GEN-LAST:event_btnGanQuyenDTActionPerformed

    private void btnThuHoiQuyenDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuHoiQuyenDTActionPerformed
//        String tenND  = txtUserName.getText();
//        TaoTaiKhoanPOJO ttk = new TaoTaiKhoanPOJO();
//        ttk.setUsrNm(tenND);
//        TaoTaiKhoanDAO.thuHoiQuyenDT(tenND);
    }//GEN-LAST:event_btnThuHoiQuyenDTActionPerformed

    private void btnNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoteActionPerformed
        // TODO add your handling code here:
        Note frmNote = new Note();
        frmNote.setVisible(true);
    }//GEN-LAST:event_btnNoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaoTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMK;
    private javax.swing.JButton btnGanQuyenDT;
    private javax.swing.JButton btnGanQuyenKN;
    private javax.swing.JButton btnGanVaiToHT;
    private javax.swing.JButton btnNote;
    private javax.swing.JButton btnTaoUser;
    private javax.swing.JButton btnThuHoiQuyenDT;
    private javax.swing.JButton btnThuHoiQuyenKN;
    private javax.swing.JButton btnThuHoiVaiToHT;
    private javax.swing.JButton btnXoaNguoiDung;
    private javax.swing.JComboBox<String> cbbTblsp;
    private javax.swing.JComboBox<String> cbbTenPrfl;
    private javax.swing.JComboBox<String> cbbTmpTblsp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNguoiDung;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
